repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      -   id: check-toml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy